# Generated by Django 4.2 on 2025-04-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_booking_travel_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='travel_guide',
        ),
    ]
