# Generated by Django 4.2 on 2025-04-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='trip_roadmap',
            field=models.TextField(blank=True, help_text='Detailed trip itinerary and planning roadmap', null=True),
        ),
    ]
